import { Component, signal, inject, OnInit } from '@angular/core';
import { CommonModule, DecimalPipe } from '@angular/common';
import { RouterLink, Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { NgxChartsModule, Color, ScaleType } from '@swimlane/ngx-charts';
import { FilterService, FilterType } from '../shared/services/filter.service';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink, NgxChartsModule],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
  providers: [DecimalPipe]
})
export class DashboardComponent implements OnInit {
  private router = inject(Router);
  private filterService = inject(FilterService);
  private http = inject(HttpClient);

  isLoading = signal(false);

  // Stats Signals
  totalRecords = signal(125430);
  dataQualityIndex = signal(94.2);
  anomaliesCount = signal(0);
  alertsCount = signal(0);
  hasHighSeverity = signal(false);
  efficiencyGain = signal(1.4);

  // Chart Data
  sourceSystemData = [
    { name: 'Kardio-DB (CSV)', value: 85000 },
    { name: 'Labor-Befunde (PDF)', value: 32000 },
    { name: 'Freetext Notes', value: 8430 }
  ];

  // Chart options
  showXAxis = true;
  showYAxis = true;
  gradient = false;
  showLegend = false;
  showXAxisLabel = true;
  yAxisLabel = 'Source System';
  showYAxisLabel = true;
  xAxisLabel = 'Records Processed';
  colorScheme: Color = {
    domain: ['#005eb8', '#10b981', '#64748b'],
    name: 'custom',
    selectable: true,
    group: ScaleType.Ordinal,
  };

  // Table Data
  recentHarmonizations = signal([
    { id: 'H-0012', source: 'Kardio-DB', records: 450, status: 'Mapped', time: '10 mins ago' },
    { id: 'H-0013', source: 'Labor-Befunde', records: 12, status: 'Low Confidence', time: '1 hour ago' },
    { id: 'H-0014', source: 'Freetext Notes', records: 3, status: 'Manual Review Required', time: '2 hours ago' },
    { id: 'H-0015', source: 'Patient Master', records: 800, status: 'Mapped', time: '5 hours ago' },
    { id: 'H-0016', source: 'Legacy EHR', records: 210, status: 'Mapped', time: '6 hours ago' }
  ]);

  ngOnInit() {
    // Reset global filter back to none when visiting dashboard
    this.filterService.setFilter('none');
    this.fetchAnomalies();
    this.fetchDashboardStats();
  }

  fetchDashboardStats() {
    this.http.get<any>('http://localhost:8000/dashboard-stats').subscribe({
      next: (data) => {
        if (data.medication_adherence !== undefined && data.medication_adherence > 0) {
          this.dataQualityIndex.set(data.medication_adherence);
        }
      },
      error: (err) => console.error('Error fetching dashboard stats', err)
    });
  }

  exportDashboardToPDF() {
    this.isLoading.set(true);
    const element = document.getElementById('dashboard-content');
    
    if (element) {
      html2canvas(element, { scale: 2, backgroundColor: '#ffffff', useCORS: true }).then((canvas: any) => {
        // PDF Configuration
        const pdf = new jsPDF('p', 'mm', 'a4');
        const imgData = canvas.toDataURL('image/png');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
        
        // Add Header Branding
        pdf.setFontSize(16);
        pdf.setTextColor(15, 23, 42); // slate-900 equivalent
        pdf.text('Smart Health Data Mapping - Automated Audit Report', 10, 15);
        
        pdf.setFontSize(11);
        pdf.setTextColor(100, 116, 139); // slate-500 equivalent
        pdf.text('Institution: Stadtspital Zürich', 10, 22);
        
        // Draw the captured DOM Image
        pdf.addImage(imgData, 'PNG', 10, 30, pdfWidth - 20, pdfHeight - 20); // 10mm padding
        
        // Add Footer timestamp and AI Branding
        const dateStr = new Date().toLocaleString();
        pdf.setFontSize(9);
        pdf.setTextColor(148, 163, 184); // slate-400
        pdf.text(`Generated by AI Mapping Engine - ${dateStr}`, 10, pdf.internal.pageSize.getHeight() - 10);
        
        pdf.save(`SmartHealth_Mapping_Report_${new Date().getTime()}.pdf`);
        this.isLoading.set(false);
      }).catch((err: any) => {
        console.error('Error generating PDF:', err);
        this.isLoading.set(false);
      });
    } else {
      this.isLoading.set(false);
    }
  }

  fetchAnomalies() {
    this.http.get<any[]>('http://localhost:8000/anomalies').subscribe({
      next: (data) => {
        this.anomaliesCount.set(data.length);
        this.hasHighSeverity.set(data.some(a => a.severity_level === 'High' || a.severity_level === 'Critical'));
        this.alertsCount.set(data.filter(a => a.category === 'Sensor Conflict').length);
      },
      error: (err) => console.error('Error fetching anomalies', err)
    });
  }

  navigateToExplorer() {
    this.router.navigate(['/anomaly-explorer']);
  }

  navigateToMapper(filter: FilterType) {
    this.isLoading.set(true);
    // Visual feedback: Simulate backend processing for 600ms
    setTimeout(() => {
      this.isLoading.set(false);
      
      if (filter === 'quality') {
        this.router.navigate(['/audit'], { queryParams: { filter: 'missing' } });
      } else {
        this.filterService.setFilter(filter);
        this.router.navigate(['/mapper']);
      }
    }, 600);
  }
}
